apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name | default "python-api" }}
  labels:
    app: {{ .Values.app.name | default "python-api" }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name | default "python-api" }}
  ports:
    - port: 80
      targetPort: {{ .Values.app.containerPort | default 8000 }}
