apiVersion: v1
entries:
  fastapi:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-02-08T22:36:34.031144771Z"
    description: A Helm chart for Kubernetes
    digest: 4a02b77224237904e99debe0a612df7aac55449df8509b69def05bfdd25c289e
    name: fastapi
    type: application
    urls:
    - http://host.docker.internal:9000/charts/fastapi-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-08T22:36:34.030499242Z"
