{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
    app.kubernetes.io/name: {{ .Values.redis.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
        app.kubernetes.io/name: {{ .Values.redis.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: {{ .Values.redis.containerPort }}

          {{- if .Values.redis.secret.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secret.name }}
                  key: REDIS_PASSWORD
          command:
            - "redis-server"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          {{- end }}

          volumeMounts:
            - name: redis-storage
              mountPath: /data

      volumes:
        {{- if and .Values.redis.enabled .Values.redis.pvc.enabled }}
        - name: redis-storage
          persistentVolumeClaim:
            claimName: {{ .Values.redis.pvc.name }}
        {{- else }}
        - name: redis-storage
          emptyDir: {}
        {{- end }}
{{- end }}
